version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - db.env
    volumes:
      - datavolume:/var/lib/postgresql/data/
  web:
    build: .
    env_file:
      - web.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - "${HOST_POST}:8000"
    depends_on:
      - db
volumes:
  datavolume:
