version: "3.9"

services:
  db:
    image: postgres
    env_file:
      db.env
  web:
    build: .
    env_file:
      web.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - "8000:8000"
    depends_on:
      - db
