# Generated by Django 3.1.5 on 2021-01-26 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weight',
            name='weight_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
