# Generated by Django 3.1.5 on 2022-01-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_lift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
