# Generated by Django 3.1.5 on 2022-01-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20220125_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='weight',
            new_name='lift_weight',
        ),
    ]
